name: Copy Changed Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Git
        run: sudo apt-get install -y git

      - name: Identify changed files
        id: changed-files
        run: |
          git fetch origin main
          git diff --name-only origin/main...HEAD > changed-files.txt
          cat changed-files.txt

      - name: Copy changed files
        run: |
          mkdir -p target-repo-root
          while IFS= read -r file; do
            if [[ -f "target-repo/$file" ]]; then
              mkdir -p "$(dirname "target-repo-root/$file")"
              cp "target-repo/$file" "target-repo-root/$file"
            fi
          done < changed-files.txt

      - name: Delete target-repo directory
        run: rm -rf target-repo

      - name: Trigger dispatch workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: ${{ github.repository }}
          event-type: push_files
