name: Copy Files and Clean Up

on:
  push:
    branches:
      - main

jobs:
  copy-and-clean:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy files from target-repo to root directory
      run: |
        mkdir -p root-dir
        cp -r target-repo/* .
      
    - name: Remove target-repo directory
      run: |
        rm -rf target-repo

    - name: Commit changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "Move files from target-repo to root directory and clean up" || echo "No changes to commit"
        git push
